# Generated by Django 3.1.2 on 2020-11-02 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=280, validators=[django.core.validators.MinLengthValidator(2, 'Make must be greater than 1 character')]),
        ),
    ]
