# Generated by Django 3.1.2 on 2020-11-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201102_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='edited_at',
        ),
    ]
